Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift
=> Fix untracked scroll view's freezing in a floating panel

FloatingPanel.podspec, Framework/Sources/Info.plist
https://github.com/SCENEE/FloatingPanel/releases/tag/v1.1.0
=> Release v1.1.0

Framework/Sources/FloatingPanel.swift
The floating panel must work well when it's moving from full position even if the tracking scroll view's
content offset isn't the top.
Ref #30
=> Fix a bug in moving interaction from full position

Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift
=> Fix navigation bar problem

Examples/Maps/Maps/ViewController.swift, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift
* Fix the surface height on orientation change 
* Fix and clean up removal interaction implementation
* Fix backdrop bugs
* Add new methods of `FloatingPanelBehavior`
* `FloatingPanelBehavior.redirectionalProgress(_:from:to:)`
* `FloatingPanelBehavior.removalProgress`
* Add `RemovablePanelLandscapeLayout` in Samples app
=> Fix orientation change on removal

Framework/Sources/FloatingPanel.swift
Disable scroll top bouncing if a user scroll down contents(no deceleration) and the scroll offset Y is less than 10.0, instead of the velocity condition(greater than 2500.0).
This change prevents potential bugs on scroll bouncing so that the scroll view tracking is more robust.
=> Fix scroll top bounce bugs

Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift
=> Add FloatingPanelController.updateLayout()

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/UIExtensions.swift
=> Fix scroll indicator hidden

FloatingPanel.podspec, README.md
I'm planning to release v1.2.0 on Now 15th.
=> Release v1.2.0

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift
* Fix a detection of a long press gesture in content VC
* Fix a SwipeActionPanGesture is not working in the tracking scroll
* Update DebugTableViewController to test it
=> Fix the gesture handling

FloatingPanel.podspec
=> Release v1.2.1

Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift
It's not enough to support intrinsic height feature. It needs `feat-modality` to fix some bugs and to polish it. So I will append `feat-modality` branch after this.
=> Feat intrinsic height

FloatingPanel.podspec
=> Release v1.2.3

.travis.yml, Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Examples/Stocks/Stocks/ViewController.swift, FloatingPanel.podspec, Framework/FloatingPanel.xcodeproj/project.pbxproj, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/FloatingPanelTransitioning.swift, Framework/Sources/FloatingPanelView.swift, Framework/Sources/UIExtensions.swift, README.md
Ref #50, #64, #73 
**EDIT**
I'm planning to release it on Dec 15.
=> Release v1.3.0(conflicts resolved )

FloatingPanel.podspec, README.md
=> Release v1.3.1

Framework/Sources/FloatingPanelTransitioning.swift
=> Fix the modal presentation

FloatingPanel.podspec
=> Release v1.3.2

Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift
=> Support full screen layout

Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelTransitioning.swift
=> Fix the presentation modally when fpc is reused

FloatingPanel.podspec
=> Release v1.3.3

Framework/Sources/FloatingPanel.swift
=> Fix issue with jumping floating panel while dragging

README.md
Hi, just started checking this repo and spotted a typo, nothing major 🙌🏻
=> Add README missing character

Framework/Sources/FloatingPanel.swift
FloatingPanelPanGestureRecognizer => floatingPanel and floatingPanel => FloatingPanelPanGestureRecognizer
=> Fix retain cycle in FloatingPanel

Framework/Sources/FloatingPanel.swift
* Fix issues on an animation interruption
* Fix the buggy top buffer dragging
=> Fix interruption

Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift
=> Change FloatingPanelLayoutAdapter.safeAreaInsets as a read-only property

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift
Fix #128
This PR will allow you to use ASCollectionNode of Texture (http://texturegroup.org/).
=> Remove swapping delegate

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelLayout.swift
=> Fix top dragging boundary

Framework/Sources/FloatingPanelController.swift
On the master, the Samples app on iPhone 5 10.3.1 crashed on launch.  68e3fd2 commit causes it. So I fixed it.
=> Fix an infinite loop crash in iOS 10

Framework/Sources/FloatingPanelBehavior.swift
Hi @SCENEE, thank you so much to keep improving this library 😍.
I'm still playing with it, and I just spotted a couple more typos, so here's the fix 😊
=> Fix FloatingPanelBehavior.swift typos

Framework/Sources/FloatingPanelController.swift
=> Allow FloatingPanelController subclassing

Examples/Samples/Sources/ViewController.swift
=> Add pages sample

FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release v1.5.1

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/GrabberHandleView.swift
This PR allows additional customization for the following parameters of the Floating Panel:
- Grabber handle height
- Grabber handle width
- Grabber handle color
- Grabber handle top offset
- Top offset of the container view
=> Grabber handle and top offset customizations

Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/GrabberHandleView.swift
Apply patches for PR #194 and add 2 fixes.
* Clean up prop naming
* Fix the content height changed by a container inset
=> Improve surface container API

Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/GrabberHandleView.swift
* Refactor FloatingPanelSurfaceView with lazy props
* Clean up code
=> Improve surface w lazy props

.gitignore, .travis.yml, Examples/Maps/Maps/ViewController.swift, Framework/FloatingPanel.xcodeproj/project.pbxproj, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/Logger.swift, Framework/TestingApp/AppDelegate.swift, Framework/TestingApp/Info.plist, Framework/TestingApp/LaunchScreen.storyboard, Framework/Tests/FloatingPanelControllerTests.swift, Framework/Tests/FloatingPanelTests.swift, Framework/Tests/FloatingPanelViewTests.swift
* Add unit tests for the next evolution.
* Make it stable on version update.
* Just now some tests are added. I'm planning to increase unit tests eventually.
* Clean up surfavec
* Fix UIVisualEffectview issue(regression) on iOS10
=> Add unit tests

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelLayout.swift
* Add FloatingPanelBehavior.allowsRubberbanding(for:)
=> Add the rubberbanding behavior for top & bottom buffer

FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release v1.6.0

FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release v1.6.1

Framework/FloatingPanel.xcodeproj/project.pbxproj, Framework/FloatingPanel.xcodeproj/xcshareddata/xcschemes/FloatingPanel.xcscheme, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Tests/FloatingPanelControllerTests.swift, Framework/Tests/FloatingPanelLayoutTests.swift, Framework/Tests/FloatingPanelSurfaceViewTests.swift, Framework/Tests/FloatingPanelTests.swift, Framework/Tests/Utils.swift
This PR is a preparation for hidden position fix and top-to-bottom panel layout.
- Add FloatingPanelLayoutTests
- (internal)Add FloatingPanelLayoutAdapter.botomMostState
- Refactor FloatingPanel.distance(to:) and FloatingPanelLayoutAdapter.topMostState
- Improve tests
=> Refactor layout adapter

FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release v1.6.2

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelLayout.swift
* Fix scroll unlock again
* Modify the guard of an animation interruption 
* Fix bottomMaxY
* Fix preserveContentVCLayoutIfNeeded()
=> Fix regressions

.travis.yml, Examples/Samples/Sources/ViewController.swift, FloatingPanel.podspec, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/Info.plist
=> Release 1.6.3

Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/UIExtensions.swift, Framework/Tests/FloatingPanelLayoutTests.swift, README.md
=> Add FloatingPanelLayout.positionReference

Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/UIExtensions.swift, Framework/Tests/FloatingPanelControllerTests.swift, README.md
Introduce `fitToBounds` content mode.
* Add `FloatingPanelController.contentMode`
* Update 'Show Detail Panel' sample
Depends on #238 and #239 
TODO
=> Feat elastic layout

Examples/Maps/Maps/ViewController.swift, Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, FloatingPanel.podspec, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/Info.plist, Framework/Tests/FloatingPanelControllerTests.swift, Framework/Tests/FloatingPanelSurfaceViewTests.swift, Framework/Tests/Utils.swift, README.md
=> Release 1.6.5

Examples/Samples/Sources/ViewController.swift, FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release 1.7.0

Framework/Sources/FloatingPanelController.swift
4ad7f11 commit causes the wrong parameter.
=> Pass parent to didMove(toParent:)

FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release 1.7.1

Framework/Sources/FloatingPanelCore.swift
To fix [the side effect](https://github.com/SCENEE/FloatingPanel/issues/293#issuecomment-582730644) on #293 
Actually It's my fault. I can't remember the reason why I added the condition.
=> Fix breaking content offset of the tracked scroll view

.github/ISSUE_TEMPLATE.md, Examples/Samples/Samples.xcodeproj/project.pbxproj, FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release 1.7.3

FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release 1.7.5

Examples/Maps/Maps/Base.lproj/Main.storyboard
'prominent' blue effect is adaptive to dark mode.
=> use 'prominent' blur effect

FloatingPanel.podspec, Framework/Sources/Info.plist
=> Release 1.7.6

FloatingPanel.podspec, Sources/Info.plist
=> Release 2.0.1

README.md
Fix FloatingPanelTransitioning -> Transitioning
=> Fix README.md Transitioning

Sources/Behavior.swift, Sources/Controller.swift, Sources/Core.swift, Sources/Transitioning.swift
=> Open the default behavior class

Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift
Hopefully this makes it a little clearer how AL can be used.
=> Work magic numbers out of Adaptive Panel (Custom Layout Guide) example

Examples/Maps/Maps/Base.lproj/Main.storyboard, Examples/Maps/Maps/SearchViewController.swift, Examples/Maps/Maps/ViewController.swift
Fix the following 2 problems in Maps sample.
* When I click on Marked Location after activating a search bar, keyboard and main FP won’t resign and disapear when table view shows up.
* The detail vc layout is invalid in iPhone 12 Pro Max.
=> Fix Maps samlpe

README.md
=> Add a description for the backdropAlpha(for:) API

Sources/Core.swift
Related to #401
Reproduction steps.
1. Run Samples.app
2. Pull up the panel for "Scroll tracking(TableView)" if touching in the grabber area.
=> Address the grabber area detection in scroll tracking

Sources/Controller.swift, Sources/Core.swift, Sources/Layout.swift
=> Fix a crash by the move animator

Sources/Core.swift
=> Stop moving a panel while the tracking table view is editing

Sources/Core.swift
=> Prevent a memory leak in a nested function

FloatingPanel.podspec, README.md, Sources/Info.plist
=> Prepare v2.3.0

FloatingPanel.podspec, Sources/Info.plist
=> Release v2.3.1

Sources/Controller.swift, Sources/Core.swift
Fix a regression for the backdrop behavior reported on #466.
=> Address #466

FloatingPanel.podspec, Sources/Info.plist
=> Release 2.4.0

Examples/Samples/Sources/ViewControllers/TabBarViewController.swift, FloatingPanel.podspec, Sources/Info.plist
=> Release 2.5.0

FloatingPanel.podspec, Sources/Info.plist
=> Release 2.5.1

FloatingPanel.podspec, Sources/Info.plist
=> Release 2.5.2

FloatingPanel.podspec, Sources/Info.plist
=> Release 2.5.3

Examples/Maps-SwiftUI/Maps/FloatingPanel/FloatingPanelView.swift
=> Fix the view index of FloatingPanelView for SwiftUI

FloatingPanel.podspec, Sources/Info.plist
=> Release 2.5.5

FloatingPanel.podspec, Sources/Info.plist
=> Release 2.6.0

Examples/Samples/Sources/ContentViewControllers/DebugTableViewController.swift, Examples/Samples/Sources/UseCases/UseCaseController.swift, Sources/Controller.swift, Sources/Core.swift
Released only for the bottom position. Maybe you have a better solution that already has been implemented? Trying to find, but can't.
Before
https://user-images.githubusercontent.com/4996231/149289842-37a3db3f-90ff-4f3d-b983-9a11a52c392f.mp4
After
https://user-images.githubusercontent.com/4996231/149289857-0665b24e-6c03-4feb-b12f-29943508b7bc.mp4
=> track scroll view bouncing

.github/workflows/ci.yml, FloatingPanel.podspec, Sources/Info.plist
=> Release 2.6.1

Sources/Core.swift
=> Fix an issue where a tracking scroll content stops and the panel doesn't move

Examples/Samples/Sources/UseCases/UseCase.swift, Examples/Samples/Sources/UseCases/UseCaseController.swift, Sources/BackdropView.swift, Sources/Controller.swift, Sources/Core.swift
=> Enable to define and use a subclass object of `BackdropView`

.github/workflows/ci.yml
Testing the new ci workflow on this PR
=> ci: use Xcode 15.2 on GitHub Actions

Examples/Samples/Sources/PanelLayouts.swift, Examples/Samples/Sources/UseCases/UseCase.swift, Examples/Samples/Sources/UseCases/UseCaseController.swift, Sources/Core.swift, Tests/CoreTests.swift
See this commend for more detail:
https://github.com/scenee/FloatingPanel/issues/661#issuecomment-2818064324
=> Address #661 issue since v2.8.0　
