scenee/FloatingPanel

Examples/Maps/Maps/Base.lproj/Main.storyboard, Examples/Maps/Maps/ViewController.swift, Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/UIComponents.swift, Examples/Samples/Sources/ViewController.swift, Examples/Stocks/Stocks/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift, README.md
- The child view controller in `FloatingPanelController` can use the bottom of safe layout guide expectedly.
- Modify `FloatingPanelController.adjustedContentInset` value
- Fix a critical bug on only full and half anchor position support
- Fix `FloatingPanelLayout.{topInteractionBuffer,bottomInteractionBuffer}`
- Modify Examples/Maps to fix a blank space and a clip of cells issue in #1.  Thank you, @jaimeealmanza!
- Improve the shadow layer of `FloatingPanelSurfaceView`
- Add a sample scene with TabBar in Samples.app.
- Update README
- Add shields
- Add TOC
- Add Notes section
- Update Usage section
=> Fix surface view height

Examples/Maps/Maps/ViewController.swift, Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Examples/Stocks/Stocks/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, README.md
FloatingPanelLayout
- Add FloatingPanelLayout default implementations to make it easy to create a custom FloatingPanelLayout object
- Change `FloatingPanelLayout .supportedPositiions` type from Array to Set
```diff
- var supportedPositions: [FloatingPanelPosition]
+ var supportedPositions: Set<FloatingPanelPosition>
```
- Add `FloatingPanelLayout` consistence check
- Change the default landscape layout to reslove #3
FloatingPanelController
- Open a pan gesture of FloatingPanelController as `FloatingPanelController.panGestureRecognizer`
- Fix failure requirements of the pan gesture
FloatingPanelBehavior
- Modify and Improve FloatingPanelBehavior protocol to be more clear.
- "present" and "dismiss" should be used for modality by convention of UIViewController. so "add" and "remove" are …
=> Improve public interface

Examples/Stocks/Stocks/Base.lproj/Main.storyboard
I add two missing constraints of the title stack view, to fix a UI issue (you can see that image I post) in your stocks app.
It looks nice on my iPhone 7 now.
Thank you for your effort! 👍
=> Add missing constraints of the title

Framework/Sources/FloatingPanelController.swift
Note that developers intend to add a floating panel into native container view controllers where it doesn't work well.
=> Add and Update preconditions of the parent VC

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift
Fix #8 
Add a removal interaction invoked when a floating pane is at the bottom position.
New APIs
- `FloatingPanelController.isRemovalInteractionEnabled`
- `FloatingPanelBehavior.removalVelocityThreshold`
- `removalInteractionAnimator(_:with)`
Changes
- Now FloatingPanelController allows to display a floating panel on only one position.
=> Add a removable interaction

Examples/Samples/Sources/ViewController.swift, Examples/Stocks/Stocks/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift
Fix #22 
- Fix a blackout of the backdrop when tip and half supported positions.
- Fix the surface view's background color is not updated when a value is set to FloatingPanelSurfaceView.backgroundColor.
=> Fix backdrop bugs

Examples/Maps/Maps/ViewController.swift, Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Examples/Stocks/Stocks/ViewController.swift, Framework/Sources/FloatingPanelController.swift, README.md
Fix #20 
`FloatingPanelController.show(_:sender)` is confusing. I don’t expect to work Show segues from a floating panel and I don't think it should work. So I'd like to deprecate the method on this PR, and replace it with `FloatingPanelController.set(contentViewController:)`. The change is planning to be merged into v1.2.0.
```diff
- fpc.show(contentVC, sender: nil)
+ fpc.set(contentViewController: contentVC)
```
~If you use "Show" or "Show Detail" segue from a floating panel, it will raise a fatal error.~
"Show" or "Show Detail" segue from a content VC of a floating panel will be handled by a view controller managing a floating panel.
Finally, `FloatingPanelController.set(contentViewController:)` might be updated to `FloatingPanelController.set(contentViewController:animated:)` to …
=> Fix show segue problem

Framework/Sources/FloatingPanel.swift, Framework/Sources/GrabberHandleView.swift
As discussed in #30, this PR resolves the issue of not being able to close the floating panel when the tracked scrollview is not at its top position.
=> Fix moving floating panel without scrolling to top of scroll view

Framework/Sources/FloatingPanelSurfaceView.swift
By removing shadowPath and putting the shadow directly onto the surface view layer instead of a sublayer, the shadow doesn't affect the content view background.
This is especially noticeable when using a `UIVisualEffectView` as the content background view on top of a map view.
See also: https://stackoverflow.com/a/53300360/235297
=> Improved shadow, not darkening content background

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift
There are critical bugs on master when a tracking scroll view has short contents.
- No top bounce 
- Slow pan gesture response to make it hard to use
- Unexpected assertion failure on orientation change
=> Fix scrolling short contents

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift
Add these delegate methods
* `func floatingPanelDidChangePosition(_ vc: FloatingPanelController) `
* ~`func floatingPanel(_ vc: FloatingPanelController, shouldMoveBy: UIPanGestureRecognizer) -> Bool`~ This could be replaced with `FloatingPanelController.panGestureRecognizer.isEnable = false` or untracking a scroll view temporarily
Fix #46
=> Improve delegate

Framework/Sources/FloatingPanel.swift
Let the floating panel stop the current animator at the interruption to continue to its interaction subsequently.
Fix #60
=> Make the animated interaction interruptible

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift
Because an interruptible animator causes a wobbling at the animation start.
when a user flick a panel quickly to move to full position nearby the position.
=> The default interaction animator should be uninterruptible

.travis.yml, Examples/Samples/Sources/ViewController.swift, Examples/Stocks/Stocks/ViewController.swift, Framework/FloatingPanel.xcodeproj/project.pbxproj, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/FloatingPanelTransitioning.swift, Framework/Sources/FloatingPanelView.swift, README.md
Now `FloatingPanelController`  can’t work independent without the parent VC because its views and layouts are coupled with the parent’s view.
If  it would be decoupled from the parent VC, a floating panel could be more portable and easy to arrange it in any view hierarchy. 
The change will let you allow to use FloatingPanelController like other native container VC like `UINavigationController`, `UITabBarViewController` etc. 
For example, you can present `FloatingPanelController` as a modality.
``` swift
let fpc = FloatingPanelController()
self.present(fpc, animated: true)
```
```swift
let fpc = FloatingPanelController()
aContainerView.addSubview(fpc.view)
fpc.view.frame = aContainer.bounds // MUST
parent.addChild(fpc)
fpc.show(animated: true) { 
self.didMove(toParent: self)
}
```
```swift …
```
=> FloatingPanelController as a Modality

Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift
Fix #76, #88 
- Any gestures don't wait for `FloatingPanelController.panGestureRecognizer`
- Add new delegate method to customize the failure requirements and simultaneousness of `FloatingPanelController.panGestureRecognizer`
```swift
public protocol FloatingPanelControllerDelegate: class {
...
func floatingPanel(_ vc: FloatingPanelController, shouldRecognizeSimultaneouslyWith gestureRecognizer: UIGestureRecognizer) -> Bool
}
```
=> Fix failure requirements

Examples/Samples/Samples.xcodeproj/project.pbxproj, Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/UIExtensions.swift, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/FloatingPanelTransitioning.swift, Framework/Sources/FloatingPanelView.swift, README.md
- Prevent layout broken of a panel added by `addPanel(toParent:belowView:animated)`
- Add "Settings" panel in Samples App
- Add "Reorder" button to show a sample to disable a panel's pan gesture in Samples App.
- Clean up storyboard and code in Samples App
=> Fix layout bugs on v1.3.0

Framework/Sources/FloatingPanel.swift
For example, a user tap the backdrop view to dismiss it while dragging
the surface view on presentation modally.
Fix #100
=> Fix a crash on tap dismissal with a second touch

Framework/Sources/FloatingPanelController.swift
Typical use case is :
```
let floatingVC = FloatingPanelController()
floatingVC.delegate = self
```
This PR allows to set the delegate straight away by using `let floatingVC = FloatingPanelController(self)`
Its true reason is that the setup code that fetches behavior / layout through delegate is called without the delegate being set is useless on `init`ing.
Another implementation could be observing the `didSet` event on delegate to do the `setUp` for `FloatingPanel`
@SCENEE what do you think of this ?
Origin : I found this issue when migrating from 1.2.x to 1.3.1 where my custom behavior is not properly used.
=> fix(delegateIgnored): Allow to set delegate on init

Framework/Sources/FloatingPanelController.swift
Fixes https://github.com/SCENEE/FloatingPanel/issues/113 
Test this as follows:
- create a floating panel with content view controller `A` that has a scroll view `alpha` with a delegate `X` (could be viewcontroller `A`)
- present the panel
- set the floating panel's content view controller to a view controller `B` with scroll view `beta` and a delegate `Y` (could be viewcontroller `B`)
- set the floating panel's content view controller back to view controller `A`
- note that the delegate of scroll view `alpha` is still `X`. Without this PR, the delegate is a `FloatingPanel` instance, instead of the original delegate `X`.
=> Restore original scroll view delegate when updating content VC

Framework/Sources/FloatingPanelLayout.swift
`FloatingPanelSurfaceView.updateContentViewMask()` causes a content to be cut off.
Fix #112
=> Expand the surface mask's height

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift
This will be released in v1.3.5.
* Don't block tap/long press gestures(Always recognize them in parallel)
* Stop interrupting a content offset of a tracking scroll view at the end of an interaction
* Fix the wrong layout update in iOS10
* Fix an interruptive animation (Now a user can use an interruptive animation safely)
* Fix backdrop handling on an animation interrupt
* Fix #133: FloatingPanel can be dragged outside safe area
=> Fix interaction

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Sources/FloatingPanelTransitioning.swift, Framework/Sources/Logger.swift, Framework/Sources/UIExtensions.swift
**FloatingPanelController**
Enable to cancel the scroll view tracking 
```diff
- public func track(scrollView: UIScrollView) {
+ public func track(scrollView: UIScrollView?) {
```
**FloatingPanelControllerDelegate**
You can stop to begin dragging on the conditions. It's useful to handle other pan gestures or touches simultaneously with a floating panel.
```diff
+ public func floatingPanelShouldBeginDragging(_:)
```
**FloatingPanelBehavior**
Add  2 methods to configure the momentum projection
```diff
+ func shouldProjectMomentum(_ fpc: FloatingPanelController, for proposedTargetPosition: FloatingPanelPosition) -> Bool`
+ func momentumProjectionRate(_ fpc: FloatingPanelController) -> CGFloat
```
**FloatingPanelFullScreenLayout**
You can configure all insets of the surface from the …
=> Improve the operability

Framework/Sources/FloatingPanelController.swift
When adding a UINavigationController to the panel, the safeAreaInsets were not respected initially. This change adds the `initial` option for the KVO observation.
=> Adds support for respecting initial safeAreaInsets.

Framework/Sources/FloatingPanelLayout.swift
The assertion didn't allow `.hidden` initial position.
Fix #150
=> Fix the layout assertion

Framework/Sources/UIExtensions.swift
* Fix 'Redundant conformance' error of UIGestureRecognizerState
* ~Change the access level for `UISpringTimingParameters(dampingRatio:frequencyResponse:initialVelocity:)`~ -> Cause 'Stock App' build error
=> Fix UI extensions

Framework/Sources/FloatingPanelSurfaceView.swift
Fix #152 
---
This change lets a user be able to escape "Ambiguous use of
'cornerRadius'" error as below, if the user defines an `cornerRadius`
property of `UIView` extension.
```swift
extension UIView {
@objc dynamic var cornerRadius: CGFloat {
get { return self.layer.cornerRadius }
set(cornerRadius) {
self.layer.masksToBounds = true
self.layer.cornerRadius = cornerRadius
}
}
}
public extension FloatingPanelSurfaceView {
@objc public dynamic var fp_cornerRadius: CGFloat {
get { return backgroundView.layer.cornerRadius }
set {
if #available(iOS 11.0, *) {
contentView?.layer.masksToBounds = true
contentView?.layer.cornerRadius = newValue
contentView?.layer.maskedCorners = [.layerMinXMinYCorner, .layerMaxXMinYCorner]
}
backgroundView.layer.masksToBounds = true …
```
=> Open FloatingPanelSurfaceView.backgroundView

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift
* Prevent an unexpected layout update
* Fix scroll fitting to make it smooth
=> Fix scroll fitting

.travis.yml, Examples/Maps/Maps.xcodeproj/project.pbxproj, Examples/Samples/Samples.xcodeproj/project.pbxproj, Examples/Stocks/Stocks.xcodeproj/project.pbxproj, FloatingPanel.podspec, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/Info.plist, Framework/Sources/UIExtensions.swift, README.md
It's time for FloatingPanel to support both of Swift 5 and Swift 4.x.  
The default Swift version becomes 5.0, but the library still supports Swift 4.0/4.1.
I'm sorry I could have supported both of 4.2 and 4.0/4.1 earlier according to #117.
But after this PR you won't bother Xcode warnings about migration to Swift 4.2 or 5.0.
This PR is planning to be released in v1.5.0.
=> [Release v1.5.0] Support both of Swift 5 and 4.2

FloatingPanel.podspec, Framework/Sources/FloatingPanelSurfaceView.swift, README.md
- Fix masking a content view unexpectedly after v1.4.0.
- Also fix #109 probably because now a content view's border isn't changed.
=> Fix surface mask

Framework/Sources/FloatingPanel.swift
Because touch events seem to be cancelled when an animator is released.
Ref #164
=> Fix a touch abort on the interaction interrupted

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanel.swift
* Fix #198 
* Add a sample for tap-to-move
* Fix the moving animation's interruption
* Avoid any tap gesture recognition while dragging a panel
=> Fix scroll lock

Framework/Sources/FloatingPanel.swift
#201 fixes the reported case in #198 but the same issue happens on other case. This PR fixes #198 issue on the other cases.
=> Avoid calling {lock,unlock}ScrollView() unexpectedly

Framework/Sources/FloatingPanel.swift
Fix #216: While closing the viewcontroller via dragging, calling floatPanelController's hide() will cause a crash.
=> Fix the crash while closeing via dragging

Framework/Sources/FloatingPanel.swift
Now the scroll tracking is working well without the scroll offset handling
at the top most position in the callback of a scroll pan gesture.
Fix #218
=> Fix closing panel during internal scroll view bounce

Framework/Sources/FloatingPanel.swift
The workaround was added to avoid `tableView(_:didSelectRowAt:)` not
being called on first tap after the moving animation. However, it
doesn't only resolved the issue, but also has side effects.
For example, it affects the seamless scrolling in dragging up a panel from
half to full after bouncing it in the bottom buffer. The problem occurs
on "Tab2" sample of "Show Tab Bar".
Moreover the UITableView issue seems to be relieved on iOS 13.
Therefore I remove the workaround.
=> Remove workaround for tableView(_:didSelectRowAt:) issue

Framework/Sources/FloatingPanelController.swift, Framework/Sources/UIExtensions.swift, Framework/Tests/FloatingPanelControllerTests.swift
On iOS13, UITraitCollection.userInterfaceStyle can be changed from .light to .dark when an app transitions to the background.
=> Fix an unexpected layout update on iOS13

Framework/Sources/FloatingPanel.swift, Framework/Sources/UIExtensions.swift, Framework/Tests/FloatingPanelTests.swift
The locking logic couldn't take care of the case where a content view controller of a FloatingPanelController object is replaced.
=> Fix the scroll indicator lock on a contentVC reset

Framework/Sources/FloatingPanel.swift
Use FloatingPanel.viewcontroller as an optional value instead of an implicitly unwrapping optional one.
=> Prevent 'unexpectedly found nil' fatal error

Framework/FloatingPanel.xcodeproj/project.pbxproj, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBehavior.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/UIExtensions.swift, Framework/Tests/FloatingPanelControllerTests.swift, Framework/Tests/FloatingPanelLayoutTests.swift, Framework/Tests/FloatingPanelPositionTests.swift, Framework/Tests/FloatingPanelSurfaceViewTests.swift, Framework/Tests/FloatingPanelTests.swift, Framework/Tests/Utils.swift
I refactored the logic to handle the anchor positions appropriately including `.hidden` by unit tests.
As a result, that makes this library robust and sophisticated. In theory, now it's able to handle more than 3 supported positions and it's easy to inverse the direction. 
That's why this is a big milestone to implement top-to-bottom panel.
Additionally, this has 2 fixes, animation interruption and the scroll locking bug by an interruption, to improve the robustness.
Related issues:  #175
=> Fix hidden position and animation interruption

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelBackdropView.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelTransitioning.swift
I think it would be useful to disable or somehow be able to configure the default tap gesture recognizer for the backdrop view.
Let's say a user of the SDK wants to configure the tap gesture handler (`#selector(handleBackdrop(tapGesture:))` so customize the action triggered when the panel gets dismissed. They can't simply add a gesture recognizer to the backdrop during `FloatingPanelController` configuration, as the default handler is configured later on and effectively overrides the user-provided event handler.
Here is a hack I had to come up to disable the default tap gesture recognizer:
```swift
public extension FloatingPanelBackdropView {
override func addGestureRecognizer(_ gestureRecognizer: UIGestureRecognizer) {
// Hack to disable the default tap gesture recognizer since it's …
```
=> Allow to disable tap on backdrop view for panel dismissal

FloatingPanel.podspec, Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/Info.plist
Bugfixes
* Fix not calling floatingPanelDidEndDecelerating delegate after interruption
* Always call startInteraction before endInteraction to keep the delegate call convention.
* Fix stopping a panel b/w anchors after an interruption
=> Release 1.6.4

Framework/Sources/FloatingPanel.swift
By #205 added dismissing by backdrop view. But `floatingPanelDidEndRemove` is not called from it.
1. build sample app and run debug it.
2. set a break point to `SampleListViewController#floatingPanelDidEndRemove`
3. tap `Show Panel Modal` on sample app
When, `floatingPanelDidEndRemove` is not called
=> Call floatingPanelDidEndRemove when dismiss with tap on backdrop view

Framework/Sources/FloatingPanel.swift, Framework/Sources/FloatingPanelController.swift
As this delegate function is called at updateLayout(to:), which is sometimes called inside an animation block, it allows clients to animate the panel.
=> Improve the documentation of floatingPanelDidChangePosition

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift
Fixes #256
I've removed `containerViewTopInsetConstraint` and `containerViewHeightConstraint` in favor of using a bottom constraint.
It's not quite clear what's the purpose of `topInteractionBuffer` and `bottomInteractionBuffer` exactly, but I tried to keep the logic intact.
=> Support bottom content inset for container view

.travis.yml, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Tests/FloatingPanelSurfaceViewTests.swift, README.md
`FloatingPanelSurfaceView.containerTopInset` is replaced by `FloatingPanelSurfaceView.containerMargins.top`.
In addition, the following changes are committed.
* Fix and rename test_surfaceView_constraintsUpdate()
* Improve test_moveTo()
=> Add FloatingPanelSurfaceView.containerMargins

Framework/FloatingPanel.xcodeproj/project.pbxproj
By default, Xcode project disables the swift module interfaces for Module stability in Swift 5.1. 
I will enable it for Carthage build.
=> Enable the swift module interfaces

Framework/FloatingPanel.xcodeproj/project.pbxproj, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelCore.swift, Framework/Sources/FloatingPanelLayout.swift, Framework/Sources/FloatingPanelSurfaceView.swift, Framework/Tests/FloatingPanelLayoutTests.swift, Framework/Tests/FloatingPanelTests.swift
"'FloatingPanel' is not a member type of 'FloatingPanel'" error happens when the lib is built on Xcode 11 series using 'Build Library for Distribution`.
To fix the error, the lib has to rename the internal object named as `FloatingPanel` according the below comment.
> It's not your fault; it's a longstanding bug/limitation in Swift that if you have a type and a framework with the same name, the name is always assumed to refer to the type. brentdax is looking at some alternate ways to provide a module name in Pitch: Fully qualified name syntax that the module interface generator will be able to use; for now, though, you can work around this issue by renaming either your framework or the type in it. :-(
See https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors …
=> Rename the internal FloatingPanel object for .swiftinterface issue

Examples/Maps/Maps/ViewController.swift, Framework/Sources/FloatingPanelController.swift, Framework/Tests/FloatingPanelControllerTests.swift
Added nearby position
A position of a user's finger, returning a finger's nearby position of surfaceView.
=> Nearby position

Examples/Maps/Maps.xcodeproj/project.pbxproj
This seems to be Xcode 11's bug of linking frameworks.
=> Fix Maps.app's crash on device after the second launch

Examples/Maps/Maps/ViewController.swift, Framework/Sources/FloatingPanelCore.swift
This issue is that a panel sometimes moved up in dragging it down if content offset of the tracking scroll view in a content view controller was greater than its top interaction buffer.
Ref. #293
=> Fix a panel's move-up while dragging it down

Framework/Sources/FloatingPanelCore.swift
* Fix floatingPanelDidEndDecelerating call
* The delegate isn't called when a decelerating animation is interrupted.
* Modify floatingPanelDidEndDragging call
* Ideally, it's better to define a delegate method like scrollViewDidEndDragging(_:willDecelerate:) in FloatingPanelControllerDelegate to notify whether a panel will be decelerated or not. However it's a broken change so I add this change as workaround. The delegate method definition will be improved on v2.0.
=> Fix delegate calls

Framework/Sources/FloatingPanelController.swift
FloatingPanelController should derives preferences of the status bar, home indicator and screen edges deferring system gestures from a content view controller, not from itself.
=> Return the child view controller to consult

README.md
FloatingPanelContrller.view => FloatingPanelController.view
=> Minor README.md typo

Examples/Samples/Sources/Base.lproj/Main.storyboard, Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelCore.swift, Framework/Sources/UIExtensions.swift
FloatingPanelController asks the delegate for the content offset of a tracked scroll view pinned when a panel moves.
If you do not implement this method, the controller uses a value of the content offset plus the content insets. This method will not be called if the controller doesn't track any scroll view.
The reason why it's added is because a visual content origin of a scroll view is not always equal to its content offset plus its content insets. One of the cases is issue #304.
You can fix #304 by returning a value for a navigation bar with a large title as below.
```
return CGPoint(x: 0.0, y: 0.0 - trackedScrollView.contentInset.top - 148.0)
```
See also "Show Navigation Controller" in the Samples app.
=> Add floatingPanel(_:contentOffsetForPinning:) delegate method

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelCore.swift
This is because the current implementation doesn't have enough failure requirements to handle pan gestures of multiple panels so that the farthest panel can't work well.
This PR fixes both of #308 and #320.
TODO:
=> Add failure requirements for multiple panels

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelCore.swift
This pr fixes the new api name from `foatingPanel` to `floatingPanel`
=> Fix api typo

.gitignore
When opening the FloatingPanel package, this folder is created. 
This folder contains what can be considered the SwiftPM version of "Xcode derived data" folder, therefore I suggest it to be ignored.
=> ignore .swiftpm/ folder

FloatingPanel.podspec, Framework/Sources/Info.plist
1.7.3 has a mistake of API name. So I release 1.7.4 for the hot fix.
=> Release 1.7.4

Framework/Sources/FloatingPanelCore.swift, Framework/Sources/FloatingPanelLayout.swift
This PR will resolve the use case of #344
=> Support the initial hidden position not including the supported positions

Framework/Sources/FloatingPanelController.swift
Fix an invalid indicator insets of the tracking scroll view if `FloatingPanelController.contentInsetAdjustmentBehavior` is set to true.
=> Fix an invalid indicator insets of the tracking scroll view

Framework/Sources/FloatingPanelController.swift
I found the memory leak profiling the Samples app. It might fix #347.
=> Fix the memory leak of FloatingPanelController object

Framework/Sources/FloatingPanelController.swift
Apply the workaround reported by @mhdhejazi to fix #330
=> fix invalid safearea insets in a table view with static cells

Framework/Sources/FloatingPanelCore.swift
Using a directional distance to calculate an animation velocity fixes an
issue where a panel's animation was wrong when a user swipes up a panel
at the top most position.
=> fix the animation velocity's sign

Framework/Sources/FloatingPanelLayout.swift, Framework/Tests/FloatingPanelLayoutTests.swift
Because {top,bottom}Y can be {less,more} than the SafeArea/Superview bounds,
if a minus value is set to the inset for {top,bottom} most position.
fix #349
=> fix {top,bottom} constant's boundary in updating panel interactively

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelController.swift, Framework/Sources/FloatingPanelCore.swift
This PR fixes the following pane behavior in a sheet modal.
- Can't drag  a panel not including a scroll view in a sheet modal
- A view controller presented modally is removed after removing the inside panel by its removal interaction.
This fixes this issue https://github.com/SCENEE/FloatingPanel/issues/274#issuecomment-632681789 (Thanks to @FlashTang), and also fixes #298 partially.
**Limitation in Sheet modal**
If a panel's content view controller has a scroll view, a sheet modal always moves when a panel is dragged. This is because a sheet modal automatically capture a scroll view gestures and the lib is not able to prevent it.
=> Fix the panel behavior in a sheet modal

README.md
- This suggestion causes the panel to be removed if a full-screen modal is presented over the top.
=> Don't remove panel on view disappearance

Framework/Sources/FloatingPanelTransitioning.swift
The cause of that is the containerViewWillLayoutSubviews() of FloatingPanelPresentationController is called in presenting a UIImagePickerViewController. As a result, a FloatingPanelController view is added unnecessarily.
By the way, the issue doesn't happen when a FloatingPanelController shows as a child view controller.
Fix #369
=> Fix an issue where keyboard opens above image picker

Framework/Sources/FloatingPanelCore.swift
Fix of quick pull down gesture. FloatingPanel was not possible to quickly drag down from `.half` or `.full` position. During quick drag down the panel came back to previous position.
=> Fix quick pull down

Examples/Samples/Sources/ViewController.swift, Framework/Sources/FloatingPanelCore.swift
If a library consumer allows a panel projectable movement with the
FloatingPanelBehavior object, the panel is able to invoke the removal
interaction when the next moving position projected the momentum is
hidden.
Resolve #334
=> Enable the removal interaction at any positions upon the conditions

Examples/Samples/Sources/ViewController.swift, Sources/Core.swift
If `moveAnimator` isn't null, `FloatingPanelPanGestureRecognizer.touchesBegan` detects `began` state quickly so that it doesn’t allow to work a tap gesture or tap action in a panel.
Resolve #392
=> Reset the moveAnimator prop after a move animation

Sources/Core.swift
Because the current threshold(10.0) makes it hard to remove a panel.
Resolve #389
=> Ease the default velocity for a panel removal

Sources/Controller.swift
Currently there is no simple way for Voice Over users to close Floating Panels that are modally presented. It is better to provide a cancel/close button that can selected by Voice Over but in the case that one isn't provided at least the escape gesture (two fingers dragged quickly back and forth in a rough "Z" shape) will work.
=> Add escape gesture to close modal for VoiceOver users

Examples/Maps/Maps/ViewController.swift
Just spotted a little typo `apearance` -> `appearance` 😄
=> Fix example typo

Sources/Behavior.swift, Sources/Core.swift
Currently, in order to change the velocity threshold for the interactive removal gesture, we need to duplicate the default code of `floatingPanel:shouldRemoveAt:with` like this:
```swift
func defaultFloatingPanel(_ fpc: FloatingPanelController, shouldRemoveAt location: CGPoint, with velocity: CGVector) -> Bool {
let threshold = CGFloat(1.5) // Changed from 5.5 -> 1.5
switch fpc.layout.position {
case .top:
return (velocity.dy <= -threshold)
case .left:
return (velocity.dx <= -threshold)
case .bottom:
return (velocity.dy >= threshold)
case .right:
return (velocity.dx >= threshold)
}
}
```
I added an optional variable `removalInteractionVelocityThreshold` to `Behavior`, which let’s the user configure the velocity threshold for the default `floatingPanel:shouldRemoveAt:with` implementation. …
=> Added optional `removalInteractionVelocityThreshold` value to `Behavior`

Examples/Maps/Maps/ViewController.swift, Sources/SurfaceView.swift, Sources/UIExtensions.swift
This PR adds support to customize the `cornerCurve` of the `containerView` 
https://user-images.githubusercontent.com/5277837/102680653-c6e64880-41ec-11eb-8501-12ff86239b0d.mov
I might be wrong, but it seems like the mask is not following the `SurfaceAppearance`'s `cornerCurve`, initially this was because `updateShadow()` was called before `updateCornerRadius()`, but even after changing that the shadow seems to not adjust to the new `cornerCurve`. Any lead would be very welcome!
Also, I'm more than happy to close this PR if this can already be achieved in other ways, thank you :)
=> Add cornerCurve option to SurfaceAppearance

Sources/Layout.swift
I applied `.defaultHigh` priority which might be safe to prevent an ambiguous layout error. But that causes this issue, so I have to use `.required` priority.
See more detail [#424 issue](https://github.com/SCENEE/FloatingPanel/issues/424).
=> Fix an issue where not dragging a panel by priority of Layout.interactionConstraint

Sources/Core.swift
I met the crash during the animation of the floating panel. I think https://github.com/SCENEE/FloatingPanel/commit/e783b9290529902157a13c2df66fbf42ef122c1d fixed a lot for it. But somehow I still saw crash happened during the animation. After investigation, I think `ownerVC` should be checked in the completion as well.
=> Fixed the crash when ownerVC is nil.

FloatingPanel.podspec, Sources/Info.plist, Sources/Logger.swift
Bumped up the minor version and added some minor improvements
=> Prepare v2.2.0

Sources/Core.swift, Sources/Transitioning.swift
This dismisses the frame 'FloatingPanel Core.move(from:to:animated:completion:)' in the following memory leaks
> BoardServices -[BSXPCServiceConnectionEventHandler remoteTarget]
> BoardServices __63+[BSXPCServiceConnectionProxy createImplementationForProtocol:]_block_invoke
These leaks happens when a panel showes and hides using "Show Multi Panel Modal" in the Samples app.
=> Fix potential leaks in presenting/dismissing a panel modally.

Sources/Core.swift, Sources/Layout.swift, Tests/CoreTests.swift
This issue occurs when a panel is swung down with all one's might.
The trigger is here.
```swift
func floatingPanelWillEndDragging(_ vc: FloatingPanelController, withVelocity velocity: CGPoint, targetState: UnsafeMutablePointer<FloatingPanelState>) {
if targetState.pointee != .full {
owner.searchVC.hideHeader(animated: true)
}
if targetState.pointee == .tip {
>>>         vc.contentMode = .static
}
}
```
However, any library user expect to affect the backdrop by this code.
And then I recondiered the reason why the backdrop alpha changes in
activateLayout(for:forceLayout:) and it's because the animation using
CAAnimation.
Therefore I decided to move the point to change the backdrop alpha into
the move animation's completion handler.
And also the responsibility of `setBackdropAlpha(of:)` was …
=> Fix backdrop flickering

Sources/Core.swift, Tests/CoreTests.swift
Because a panel's pan gesture becomes enabled in showing it even after it is disabled.
Related https://github.com/scenee/FloatingPanel/discussions/485
=> Make the pan gesture keep disabled

Examples/Samples/Sources/ViewControllers/DebugTableViewController.swift
Noticed this while looking through the samples on an iPad.
I'd prefer to use the `UITableViewCell` as the `sourceView`, but that would be more work.
=> Fix crash in Samples app on iPad

Examples/Maps/Maps/ViewController.swift
I don't remember the reason why the example code do that. This code causes #511 so I decide to remove it.
=> Stop changing the content mode whose panel is attracting

Sources/Controller.swift, Sources/SurfaceView.swift, Tests/SurfaceViewTests.swift
They were set to .required - 1 is #359, which fixed #294.
However #294 was an issue on . fitToBounds content mode. So if your panel’s content mode is .static, I should set their priorities to .required on .static content mode because of #444 and #515.
=> Change constraint priorities of the content view on the default content mode

Examples/Maps-SwiftUI/Maps/SearchPanelPhoneDelegate.swift
Examples/Maps-SwiftUI/Maps/SearchPanelPhoneDelegate.swift add missing import UIKit
=> fix: add missing import UIKit

Sources/SurfaceView.swift
With Xcode 14 Beta 1 library fails to compile with following error
```
Stored properties cannot be marked potentially unavailable with `@available`
```
Because `CALayerCornerCurve` is not marked with any `@available` annotation it is possible to declare private optional storage of it.
With this change everything compiles.
=> Fix `cornerCurve` property availability compilation fail

Sources/Transitioning.swift
This change is a possible fix for the crash reported in #542
=> Ensure the current state is hidden in presenting it as a modality

Sources/Transitioning.swift
This resolves #561. The solution of #551 has a side effect on the case of #561, so I replace the solution with fatalError.
Instead of continuing to work a modal presentation transition even if it's not `.hidden` state, it just crash using the fatalError and the error message as a programmer error.
=> Replace PR #551 change using fatalError()

.github/workflows/ci.yml, FloatingPanel.podspec, Sources/Info.plist
=> Release 2.5.4

Examples/Maps-SwiftUI/Maps-SwiftUI.xcodeproj/project.pbxproj, Examples/Maps/Maps.xcodeproj/project.pbxproj, Examples/Samples/Samples.xcodeproj/project.pbxproj, Examples/SamplesObjC/SamplesObjC.xcodeproj/project.pbxproj, Examples/Stocks/Stocks.xcodeproj/project.pbxproj, FloatingPanel.xcodeproj/project.pbxproj
When running an app built with xcode14 on iOS11, the following error occurs and crashes.
```
dyld: Library not loaded: /usr/lib/swift/libswiftCoreGraphics.dylib
Referenced from: /private/var/containers/Bundle/Application/0B28F8D6-D8CE-400B-98B7-052EAD3FB923/xxxxxx.app/Frameworks/FloatingPanel.framework/FloatingPanel
Reason: image not found
```
=> iOS11 Crash in XCode14 add libswiftCoreGraphics.dylib

Sources/Controller.swift, Sources/Core.swift, Tests/CoreTests.swift, Tests/TestSupports.swift
This fixes https://github.com/scenee/FloatingPanel/issues/572. The main change is that `true` is passed as a `forceLayout` parameter into `viewWillTransition(to:with:)` callbacks.
Because it's necessary for the backdrop alpha's update when the view size or its size classes changes.
This also fixes a regression by https://github.com/scenee/FloatingPanel/commit/9c45c311901b90be90653aff63871ea751fae171.
```diff
-        layoutAdapter.activateLayout(for: state, forceLayout: true)
+        layoutAdapter.activateLayout(for: state, forceLayout: forceLayout)
```
The behavior before the above second change indicates that the method is working well even when `forceLayout` is set to `true` in their callbacks.
=> Fix the backdrop alpha issue (#572)

.github/workflows/ci.yml
I added Xcode 14.1 environment, which will be the minimum requirement to submit iOS and iPadOS apps to the App Store on April 2023.
https://developer.apple.com/news/?id=z1erkhzr
=> ci: add xcode 14.1 env in GitHub Actions

Sources/Core.swift, Sources/Extensions.swift, Tests/CoreTests.swift
Commit 448fc5c has a critical regression in scroll tracking that can cause the scroll content to bounce after moving a panel, for example, pulling down it from full to half state. 
By re-investigating #524, I found that this problem only occurred with the fitToBounds content mode(and a small scroll view content).
Therefore I fixed it in the more specific way.
=> [Revised] Fix an issue scrolling jumps with a small scroll view content (#524)

Examples/Samples/Sources/UseCases/UseCase.swift, Examples/Samples/Sources/UseCases/UseCaseController.swift, Sources/Controller.swift
`dismissalTapGestureRecognizer `didn't work when the panel is added into UIWindow directly as its subview. This PR fixes this issue and also adds the use case in Samples.app.
Resolve #590
=> Fixes an issue where dismissalTapGestureRecognizer doesn't work in one case

Sources/Core.swift
This change is what fixed a certain bug for our app: Whenever we had the FloatingPanel at full height and dragged it down, the content (which was a scroll view) locked at a negativ offset. It was most obvious when the whitespace was large, hence the offset was something around `-100.0`. At the same time, the contents (like buttons) were non-interactive.
Now, this behavior only surfaced recently when we needed to update our SwiftUI wrapper code. Previously, we used the code from the Map-SwiftUI example. However, once we added a TextField, the content's were not updated based on the text variable.
The solution was to update the content's `UIHostingController`'s `rootView`. Happy to hear if there are more efficient changes that can be done to the example code.
Please take a look at the …
=> Suggestion: Fix scrollview content staying non-interactive after slowly swiping down

Sources/Core.swift, Sources/Extensions.swift
Use a separate `scrollLocked` var instead of abusing the scrollView's properties to store the locked state.
Fixes an issue where the scroll indicators were no longer visible because `lockScrollView()` was executed twice before `unlockScrollView()` was called (due to the user changing `showsVerticalScrollIndicator` mid-animation).
=> Fix scroll locking behavior

Examples/Samples/Samples.xcodeproj/project.pbxproj, Examples/Samples/Sources/ContentViewControllers/DebugListCollectionViewController.swift, Examples/Samples/Sources/ContentViewControllers/UnavailableViewController.swift, Examples/Samples/Sources/UseCases/UseCase.swift, Examples/Samples/Sources/UseCases/UseCaseController.swift, Sources/Core.swift
=> Fix the scroll tracking of WKWebView on iOS 17.4

Sources/Core.swift
`pre > .zero` condition is not working for `FloatingPanelLayoutAnchor` with zero or minus `absoluteInset`. In fact, the condition is not needed here.
=> Fix an inappropriate condition to determine scrolling content (#633)

FloatingPanel.xcodeproj/project.pbxproj, Sources/Behavior.swift, Sources/Controller.swift, Sources/Core.swift, Sources/Layout.swift, Sources/LayoutAnchoring.swift, Sources/LayoutProperties.swift, Sources/Position.swift, Sources/Transitioning.swift
Added `any` to each protocols to resolve `existential-any` build errors on Swift 6.  
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0335-existential-any.md
=> Fix existential-any for Swift6

Sources/Transitioning.swift
This PR modifies the `transitionDuration(using:)` method in `FloatingPanelController` to return `0.0` instead of calling `fatalError` when the `FloatingPanelController` instance is not found. This change is crucial for several reasons:
1. **Avoiding Crashes in Production**: Using `fatalError` in production can lead to unexpected crashes, which are detrimental to user experience. It's safer to return a default value like `0.0` and handle the scenario gracefully.
2. **Improved Stability**: By returning `0.0`, the application can continue running, allowing for better stability and user satisfaction. This approach also aligns with the principle of fail-safety, where the system continues operating under error conditions.
3. **Real-World Case**: In our large-scale project, we encountered a …
=> Removing fatal error in method transitionDuration

Sources/Core.swift
This will resolve #633's 2nd issue.
=> Disallow interrupting the panel interaction while bouncing over the most expansion state

.circleci/config.yml, .github/workflows/ci.yml, Sources/Core.swift, Sources/Logging.swift, Tests/CoreTests.swift
=> Reset `initialScrollOffset` after the attracting animation ends
